#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.

# Remove the default Nginx configuration
rm /etc/nginx/sites-enabled/default

# Create a symbolic link to enable the default configuration
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart Nginx service
service nginx restart
